[formats]
# %d = date/time, %V = log level, %c = category, %m = message, %n = newline
concise = "%d(%H:%m:%s) [CLIENT] [%V] %c: %m%n"

[rules] # all categories are listed here
main_thread.* "../log/client/client.log"; concise
rcv_thread.* "../log/client/client.log"; concise
ticker_thread.* "../log/client/client.log"; concise


# send anything else to a general utcp log and print to console
*.* "log/client/utcp.log"; concise
*.* >stdout; concise
