[formats]
concise = "%d(%H:%m:%s) [CLIENT] [%V] %c: %m%n"
csv_format = "%d(%s).%ms,%m%n"

[rules] # filepaths are relative to the /build dir
main_thread.*   "log/client.log"; concise
listen_thread.*    "log/client.log"; concise
ticker_thread.* "log/client.log"; concise
cc_data.* "log/client_cwnd_output.csv"; csv_format

# print logs to the terminal too
*.* >stdout; concise
