[formats]
concise = "%d(%s).%ms [CLIENT] [%V] %c: %m%n"
cc_csv_format = "%d(%s).%ms,%m%n"
rtt_csv_format = "%d(%s).%ms,%m%n"
lstm_csv_format = "%m%n"

[rules] # filepaths are relative to the /build dir
#main_thread.*   "log/client.log"; concise
#listen_thread.*    "log/client.log"; concise
#ticker_thread.* "log/client.log"; concise

# events.csv format: TIME,EVENT,CWND,SSTHRESH
cc_data.* "log/events.csv"; cc_csv_format

#rtt.csv format: TIME,RTT_SAMPLE,SRTT,RTTVAR
rtt_data.* "log/rtt.csv"; rtt_csv_format

lstm_logger.* "log/lstm_output.csv"; lstm_csv_format

# print logs to the terminal too
#*.* >stdout; concise
