[formats]
concise = "%d(%H:%m:%s) [SERVER] [%V] %c: %m%n"

[rules] # filepaths are relative to the /build dir
main_thread.*   "log/server/server.log"; concise 
listen_thread.* "log/server/server.log"; concise
ticker_thread.* "log/server/server.log"; concise

# A catch-all to send anything else to a general utcp log (help identify incorrect logs)
*.* "log/server/app.log"; concise
*.* >stdout; concise
