[formats]
concise = "%d(%H:%m:%s) [SERVER] [%V] %c: %m%n"

[rules]
# Route specific categories to specific files inside /log/server/
ring_buffer.* "log/server/ring_buffer.log"; concise
handshake.* "log/server/handshake.log"; concise

# Catch-all
*.* "log/server/app.log"; concise
*.* >stdout; concise