[formats]
concise = "%d(%H:%m:%s) [SERVER] [%V] %c: %m%n"

[rules] # filepaths are relative to the /build dir
main_thread.*   "log/server/server.log"; concise 
listen_thread.* "log/server/server.log"; concise
ticker_thread.* "log/server/server.log"; concise

# print logs to the terminal too
*.* >stdout; concise
